### PR TITLE
Replace "Why Use FP" section boiler-plate notes with real notes and new pictures

### PR DESCRIPTION
**Pull request by eleanor-byhook**

### CODE REVIEW

**Comment by bradmurphy** [comment]
I think we should be consistent with any code, it should all be within the code box that reveal uses.

**Comment by eleanor-byhook** [comment]
Oh you mean rather than using a screenshot of the code?  Sure, I can make that change.

**Comment by eleanor-byhook** [comment]
@bradmurphy updated

**Comment by bradmurphy** [comment]
Score, looks good.

**Pull request merged**
